name = "Gruppe Adler Clip Overlay";
dir = "@grad_clipOverlay";
description = "Gruppe Adler Clip Overlay v0.2.1";
author = "y0014984";
logo = "logo_ca.paa";
logoOver = "logo_active_ca.paa";
tooltip = "Gruppe Adler Clip Overlay";
tooltipOwned = "Gruppe Adler Clip Overlay";
picture = "overview_co.paa";
actionName = "GitHub";
action = "https://github.com/gruppe-adler/grad_clipOverlay";
overview = "<br/><t align='center' size='0.75'>Visit Gruppe Adler on <t href='https://gruppe-adler.de/'>our Website</t> | <t href='http://discord.gruppe-adler.de'>Discord</t> | <t href='https://www.youtube.com/user/gruppeadler'>YouTube</t> | <t href='https://twitter.com/Gruppe_Adler'>Twitter</t></t><br/><br/>Gruppe Adler Clip Overlay is a mod for Arma 3, which adds a overlay for clips/videos.";
hideName = 0;
hidePicture = 0;
dlcColor[] = {0.8196, 0.5529, 0.1216, 1};
logoSmall = "logo_small_ca.paa";